### ISSUE TITLE
boolean error

### ISSUE THREAD

**Issue by geekwise-maria-navarro** [geekwise-maria-navarro/django.drf.react.bank.project#4]
![heroku](https://user-images.githubusercontent.com/57422170/71375151-20804c80-2572-11ea-976f-f1fd1ef7dba6.png)

**Comment by climateamante** [comment]
![](https://user-images.githubusercontent.com/57422170/71300240-bf753080-2347-11ea-8ada-2f353361bd8b.png)

**Comment by geekwise-maria-navarro** [comment]
thanks @climateamante
